""" Represents the data dictionaries used to determine lengths of procedures """
from ScheduleColors import BlockColors

procedureIDs = { #What the 2 key value is set to for each procedure block
    "Empty" : 0,
    "Break" : 1,
    "Custom" : 2,
    "Regular" : 3,
    "Laser" : 4,
    "Premium" : 5,
    "Trabeculectomy" : 6, 
    "Vivity" : 7,
    "Toric/ORA" : 8,
    "Goniotomy" : 9,
    "Micropulse" : 10,
    "Canaloplasty" : 11,
    "Stent" : 12,
    "Shunt" : 13,
    "PanOptix" : 14,
    "XEN" : 15,
    "Trimox" : 16,
    "XENRevision" : 17,
    "WoundRevision" : 18,
    "MIGS" : 19,
}

procedureList = [ #What the 2 key value is set to for each procedure block
    "Empty",
    "Break",
    "Custom",
    "Regular",
    "Laser",
    "Premium",
    "Trabeculectomy", 
    "Vivity",
    "Toric/ORA",
    "Goniotomy",
    "Micropulse",
    "Canaloplasty",
    "Stent",
    "Shunt",
    "PanOptix",
    "XEN",
    "Trimox",
    "XENRevision",
    "WoundRevision",
    "MIGS",
]

procedureDesc = {
    "Regular" : "Regular",
    "Laser" : "Laser",
    "Premium" : "Premium",
    "Custom" :  "Custom",
    "Break" : "Surgeon Break",
    "Trabeculectomy" : "Trabeculectomy", 
    "Vivity" : "Vivity",
    "Toric/ORA" : "TORIC",
    "Goniotomy" : "MIGS",
    "Micropulse" : "Micropulse",
    "Canaloplasty" : "MIGS",
    "Stent" : "MIGS",
    "Shunt" : "Shunt",
    "PanOptix" : "PanOptix",
    "XEN" : "XEN",
    "Trimox" : "Regular",
    "XENRevision" : "XEN Revision",
    "WoundRevision" : "Wound Revision",
    "MIGS" : "MIGS",
}

blockTimes = {
    "Regular" : 1,
    "Laser" : 1.25,
    "Premium" : 1.5,
    "Custom" :  1,
    "Break" : 2,
    "Trabeculectomy" : 3, 
    "Vivity" : 1.5,
    "Toric/ORA" : 1.5,
    "Goniotomy" : 1.25,
    "Micropulse" : 1.25,
    "Canaloplasty" : 1.25,
    "Stent" : 1.25,
    "Shunt" : 4,
    "PanOptix" : 1.5,
    "XEN" : 3,
    "Trimox" : 1,
    "XENRevision" : 2,
    "WoundRevision" : 1.5,
    "MIGS" : .25,
}

blockColors = {
    "Regular" : BlockColors.REGULAR.value,
    "Laser" : BlockColors.LASER.value,
    "Premium" : BlockColors.PREMIUM.value,
    "Custom" : BlockColors.CUSTOM.value,
    "Break" : BlockColors.BREAK.value,
    "Trabeculectomy" : BlockColors.TRABECULECTOMY.value, 
    "Vivity" : BlockColors.VIVITY.value,
    "Toric/ORA" : BlockColors.TORIC_ORA.value,
    "Goniotomy" : BlockColors.GONIOTOMY.value,
    "Micropulse" : BlockColors.MICROPULSE.value,
    "Canaloplasty" : BlockColors.CANALOPLASTY.value,
    "Stent" : BlockColors.STENT.value,
    "Shunt" : BlockColors.SHUNT.value,
    "PanOptix" : BlockColors.PANOPTIX.value,
    "XEN" : BlockColors.XEN.value,
    "Trimox" : BlockColors.TRIMOX.value,
    "XENRevision" : BlockColors.TORIC_ORA.value,
    "WoundRevision" : BlockColors.TRIMOX.value,
    "MIGS" : BlockColors.CANALOPLASTY.value,
}